f = open('src/routes/index.tsx', 'r', encoding='utf-8')
c = f.read()
f.close()

idx = c.find('import { useStaggerReveal')
if idx < 0:
    print('ERROR: import location not found')
    exit(1)

line_end = c.find('\n', idx)
new_imports = 'import { useMutation } from \"@tanstack/react-query\";\nimport { submitContact } from \"@/lib/api/contact.server\";\n'
c = c[:line_end+1] + new_imports + c[line_end+1:]

# Now find the Contact function and add form state
fn_start = c.find('export function Contact()')
if fn_start < 0:
    print('ERROR: Contact function not found')
    exit(1)

# Add form state management at the beginning of Contact
hook_needle = 'export function Contact() {'
hook_replacement = '''export function Contact() {
  const [form, setForm] = useState({ name: '', company: '', email: '', phone: '', industry: '', service: '', brief: '' });
  const [formStatus, setFormStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const mutation = useMutation({
    mutationFn: submitContact,
    onSuccess: (result) => {
      if (result.success) {
        setFormStatus('success');
        setForm({ name: '', company: '', email: '', phone: '', industry: '', service: '', brief: '' });
        setTimeout(() => setFormStatus('idle'), 5000);
      } else {
        setFormStatus('error');
      }
    },
    onError: () => setFormStatus('error'),
  });

  const updateField = (field: string, value: string) =>
    setForm((prev) => ({ ...prev, [field]: value }));
'''
c = c.replace(hook_needle, hook_replacement)

# Add formStatus feedback JSX before the submit button
old_submit = '<button\n              type=\"submit\"'
new_submit = '''{formStatus === 'success' && (
              <div className=\"flex items-center gap-3 px-5 py-3 rounded-lg bg-emerald-soft/20 text-emerald-soft text-sm\">
                <svg className=\"!size-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path strokeLinecap=\"round\" strokeLinejoin=\"round\" strokeWidth={2} d=\"M5 13l4 4L19 7\" /></svg>
                Thank you! We'll be in touch within one working day.
              </div>
            )}
            {formStatus === 'error' && (
              <div className=\"flex items-center gap-3 px-5 py-3 rounded-lg bg-red-500/10 text-red-600 text-sm\">
                <svg className=\"!size-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path strokeLinecap=\"round\" strokeLinejoin=\"round\" strokeWidth={2} d=\"M12 9v2m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z\" /></svg>
                Something went wrong. Please email us directly at habigo360@gmail.com
              </div>
            )}
            <button
              type=\"submit\"'''
c = c.replace(old_submit, new_submit)

# Replace the form element to wire up fields and submit handler
old_form = '<form\n            onSubmit={(e) => e.preventDefault()}\n            className=\"lg:col-span-7 bg-ivory text-foreground p-8 lg:p-12 rounded-sm space-y-6\"'
new_form = '''<form
            onSubmit={(e) => {
              e.preventDefault();
              const target = e.target as HTMLFormElement;
              const fd = new FormData(target);
              const data = {
                name: fd.get('name') as string || '',
                company: fd.get('company') as string || '',
                email: fd.get('email') as string || '',
                phone: fd.get('phone') as string || '',
                industry: fd.get('industry') as string || '',
                service: fd.get('service') as string || '',
                brief: fd.get('brief') as string || '',
              };
              mutation.mutate({ data });
            }}
            className=\"lg:col-span-7 bg-ivory text-foreground p-8 lg:p-12 rounded-sm space-y-6\"'''
c = c.replace(old_form, new_form)

# Add name attributes to form fields
# Field label="Full Name" -> Field label="Full Name" -> the <input> needs a name
# These are generated by the Field component which doesn't take a name prop yet
# Let's update each Field call to pass name

# Full Name
old_fn = '<Field label=\"Full Name\" placeholder=\"Alex Rivera\" />'
new_fn = '<Field label=\"Full Name\" placeholder=\"Alex Rivera\" name=\"name\" />'
c = c.replace(old_fn, new_fn)

old_company = '<Field label=\"Company\" placeholder=\"Brand or studio\" />'
new_company = '<Field label=\"Company\" placeholder=\"Brand or studio\" name=\"company\" />'
c = c.replace(old_company, new_company)

old_email = '<Field label=\"Email\" type=\"email\" placeholder=\"you@brand.com\" />'
new_email = '<Field label=\"Email\" type=\"email\" placeholder=\"you@brand.com\" name=\"email\" />'
c = c.replace(old_email, new_email)

old_phone = '<Field label=\"Phone\" placeholder=\"+91 ...\" />'
new_phone = '<Field label=\"Phone\" placeholder=\"+91 ...\" name=\"phone\" />'
c = c.replace(old_phone, new_phone)

old_industry = '<Field label=\"Industry\" placeholder=\"Hospitality, F&B, Fashion...\" />'
new_industry = '<Field label=\"Industry\" placeholder=\"Hospitality, F&B, Fashion...\" name=\"industry\" />'
c = c.replace(old_industry, new_industry)

# Add name to select
old_select = '<select className=\"w-full bg-transparent border-b border-border py-2.5 focus:border-emerald-deep outline-none text-sm transition-colors\">'
new_select = '<select name=\"service\" className=\"w-full bg-transparent border-b border-border py-2.5 focus:border-emerald-deep outline-none text-sm transition-colors\">'
c = c.replace(old_select, new_select)

# Add name to textarea
old_textarea = '<textarea\n                rows={4}\n                placeholder=\"A few lines about your goals, timeline and budget range...\"'
new_textarea = '<textarea\n                name=\"brief\"\n                rows={4}\n                placeholder=\"A few lines about your goals, timeline and budget range...\"'
c = c.replace(old_textarea, new_textarea)

# Also update the Field component to accept and pass a name prop
old_field_fn = 'function Field({\n  label,\n  placeholder,\n  type = \"text\",\n}: {\n  label: string;\n  placeholder?: string;\n  type?: string;\n}) {'
new_field_fn = 'function Field({\n  label,\n  placeholder,\n  type = \"text\",\n  name,\n}: {\n  label: string;\n  placeholder?: string;\n  type?: string;\n  name?: string;\n}) {'
c = c.replace(old_field_fn, new_field_fn)

old_input = '<input\n        type={type}\n        placeholder={placeholder}\n        className=\"w-full bg-transparent border-b border-border py-2.5 focus:border-emerald-deep outline-none text-sm transition-colors\"\n      />'
new_input = '<input\n        type={type}\n        placeholder={placeholder}\n        name={name}\n        className=\"w-full bg-transparent border-b border-border py-2.5 focus:border-emerald-deep outline-none text-sm transition-colors\"\n      />'
c = c.replace(old_input, new_input)

f = open('src/routes/index.tsx', 'w', encoding='utf-8')
f.write(c)
f.close()
print('SUCCESS: All contact form updates applied')
